# 1.3. Introducing the multidimensional array in NumPy for fast array computations

In [3]:
import random
import numpy as np

In [4]:
n = 1000000
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]

In [5]:
x[:3], y[:3]

([0.6742016977978244, 0.6706533636400015, 0.47924485740870115],
 [0.7710165248042705, 0.8581879648483182, 0.4948913823814307])

In [7]:
z = [x[i] + y[i] for i in range(n)]
z[:3]

[1.4452182226020949, 1.5288413284883196, 0.9741362397901319]

In [8]:
%timeit [x[i] + y[i] for i in range(n)]

100 ms ± 670 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
xa = np.array(x)
ya = np.array(y)

In [12]:
xa[:3]

array([0.6742017 , 0.67065336, 0.47924486])

In [13]:
za = xa + ya
za[:3]

array([1.44521822, 1.52884133, 0.97413624])

In [14]:
%timeit xa + ya

442 µs ± 14.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
%timeit sum(x)  # pure Python

3.94 ms ± 4.44 µs per loop (mean ± std. dev. of 7 runs
    100 loops each)


In [15]:
%timeit np.sum(xa)  # NumPy

194 µs ± 525 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [16]:
d = [abs(x[i] - y[j])
     for i in range(1000)
     for j in range(1000)]

In [18]:
d[:3]

[0.09681482700644617, 0.1839862670504938, 0.17931031541639364]

In [19]:
da = np.abs(xa[:1000, np.newaxis] - ya[:1000])

In [20]:
da

array([[0.09681483, 0.18398627, 0.17931032, ..., 0.17661962, 0.14974636,
        0.06520317],
       [0.10036316, 0.1875346 , 0.17576198, ..., 0.18016796, 0.14619802,
        0.06165484],
       [0.29177167, 0.37894311, 0.01564652, ..., 0.37157646, 0.04521049,
        0.12975367],
       ...,
       [0.15022567, 0.06305423, 0.42635081, ..., 0.07042087, 0.39678685,
        0.31224367],
       [0.1933773 , 0.10620586, 0.46950245, ..., 0.11357251, 0.43993849,
        0.3553953 ],
       [0.05054359, 0.13771503, 0.22558156, ..., 0.13034838, 0.1960176 ,
        0.11147441]])

In [21]:
%timeit [abs(x[i] - y[j]) \
         for i in range(1000) \
         for j in range(1000)]

130 ms ± 419 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [17]:
%timeit np.abs(xa[:1000, np.newaxis] - ya[:1000])

1.54 ms ± 48.9 µs per loop (mean ± std. dev. of 7 runs
    1000 loops each)
